name: glueviz

dependencies:
  - pyqt
  - numpy
  - matplotlib=1.5.0
  - pandas
  - astropy
  - dill
  - h5py
  - scipy
  - scikit-image
  - ipython
  - ipykernel
  - qtconsole
  - traitlets
  - pygments
  - pyzmq
  - mock
  - pytest
  - python>=3
