language: c


sudo: false

addons:
  apt:
    packages:
      - rubygems

notifications:
  email: false

env:
  global:
    - PYTEST_ARGS="--cov glue"
    - MATPLOTLIB_VERSION=1.5.0
    - NUMPY_VERSION=1.10
    - IPYTHON_VERSION=4
    - NO_CFG_FILES=false
    - QT_PKG=pyqt
    - SETUP_XVFB=True
    - CONDA_DEPENDENCIES="pip dill ipython matplotlib scipy cython h5py pygments pyzmq scikit-image pandas sphinx=1.2.3 xlrd pillow pytest mock coverage pyyaml requests sphinx_rtd_theme"
    - PIP_DEPENDENCIES="pytest-cov coveralls pyavm astrodendro awscli ginga"
    - secure: NvQVc3XmmjXNVKrmaD31IgltsOImlnt3frAl4wU0pM223iejr7V57hz/V5Isx6sTANWEiRBMG27v2T8e5IiB7DQTxFUleZk3DWXQV1grw/GarEGUawXAgwDWpF0AE/7BRVJYqo2Elgaqf28+Jkun8ewvfPCiEROD2jWEpnZj+IQ=
    - secure: "SU9BYH8d9eNigypG3lC83s0NY6Mq9AHGKXyEGeXDtz1npJIC1KHdzPMP1v1K3dzCgl1p6ReMXPjZMCENyfNkad/xvzTzGk0Nu/4BjihrUPV6+ratVeLpv0JLm8ikh8q+sZURkdtzUOlds+Hfn5ku4LdpT87tcKHY9TINAGA34ZM="
    - AWS_ACCESS_KEY_ID: AKIAI2ERWDHLW3W24X3A
    - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY_ID

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:


        - os: linux
          env:
            - PYTHON_VERSION=2.7
            - ASTROPY_VERSION=1.0
            - DOC_TRIGGER=1
            - APP_TRIGGER=1
            - PYTEST_ARGS="--cov glue --no-optional-skip"
            - NO_CFG_FILES=true



before_install:

  # The PyQt5 package is in the astrofrog channel
  - if [[ $QT_PKG == pyqt5 ]]; then export CONDA_CHANNELS="astropy-ci-extras astrofrog"; fi

  # Prepare dependency list
  - if [[ $QT_PKG != False ]]; then export CONDA_DEPENDENCIES="$QT_PKG "$CONDA_DEPENDENCIES; fi

  # Special cases depending on IPython version
  - if [[ $IPYTHON_VERSION == 4 ]]; then export CONDA_DEPENDENCIES="qtconsole ipykernel "$CONDA_DEPENDENCIES; fi

  # Documentation dependencies
  - if [ $DOC_TRIGGER ]; then export PIP_DEPENDENCIES="astropy-helpers linkchecker "$PIP_DEPENDENCIES; fi

  # Install ci-helpers and set up conda
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

  # setup tools to trigger mac buildbot
  - if [ $APP_TRIGGER ]; then source .setup_app_trigger.sh; fi
  - if [ $TRAVIS_BRANCH = master ]; then export S3_DIR=latest; else export S3_DIR=$TRAVIS_BRANCH; fi

  # now set up a plugin configuration file with some plugins disabled. This is
  # to make sure that when we run the tests, glue will ignore this
  # configuration and will instead run tests for all plugins.
  - if [[ $NO_CFG_FILES == false ]]; then mkdir ~/.glue; printf "[plugins]\nspectrum_tool = 0\n" >> ~/.glue/plugins.cfg; fi

install:

  - LC_ALL=C

  # Uninstall PyQt if we are using PySide or PyQt5
  - if [ $QT_PKG == pyside ]; then conda remove pyqt sip || true; fi
  - if [ $QT_PKG == pyqt5 ]; then conda remove pyqt qt || true; fi

  - if [[ $QT_PKG == pyqt5 ]]; then
      export QT_QPA_PLATFORM_PLUGIN_PATH=$HOME/miniconda/envs/test/lib/qt5/plugins/platforms;
      export QT_DEBUG_PLUGINS=1;
    fi

  # Uninstall any version of Qt if QT_PKG is False, and remove all qt
  # sub-directories
  - if [[ $QT_PKG == False ]]; then
      conda remove --no-pin pyqt || true;
      conda remove --no-pin pyside || true;
      conda remove --no-pin pyqt5 || true;
      conda remove --no-pin qt || true;
      conda remove --no-pin qt5 || true;
      find . -name "qt" -type d -exec rm -r {} \; || true;
      rm glue/external/qt.py || true;
    fi

  # We need to install glue in order to make sure that the entry points are
  # installed
  - python setup.py install

script:

  - python setup.py test -a "$PYTEST_ARGS";

  # In the following, we use separate if statements for each line, to make
  # sure the exit code from each one is taken into account for the overall
  # exit code.
  - if [ $DOC_TRIGGER ]; then cd doc; make html 2> warnings.log; cd ..; fi
  - if [ $DOC_TRIGGER ]; then cat doc/warnings.log; fi
  # make sure stderr was empty, i.e. no warnings
  - if [ $DOC_TRIGGER ]; then test ! -s doc/warnings.log; fi
  - if [ $DOC_TRIGGER ]; then linkchecker --ignore-url=".*fontawesome_webfont.*" doc/_build/html; fi

after_success:

  # Coverage testing
  - if [[ $QT_PKG != False ]]; then coveralls; fi

  # Trigger the building of the MacOS X app in the Travis-MacGlue repo
  - if [ $APP_TRIGGER ]; then ./.trigger_app_build.sh; fi

  # For any branch (but not pull requests), upload the docs to s3
  - if [[ $DOC_TRIGGER && $TRAVIS_SECURE_ENV_VARS == true && $TRAVIS_PULL_REQUEST == false ]]; then cd doc && make s3 && cd ../; fi

  # For the master branch, also upload the docs to the 'latest' URL
  - if [[ $DOC_TRIGGER && $TRAVIS_SECURE_ENV_VARS == true && $TRAVIS_BRANCH == master && $TRAVIS_PULL_REQUEST == false ]]; then cd doc && make s3latest && cd ../; fi