jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux
    tox_pre: DISPLAY=:99.0
    envs: [py36-pyqt511, py36-pyqt512]

- template: azure-template.yml
  parameters:
    name: MacOSX
    os: macosx
    envs: [py36-pyqt59]

- template: azure-template.yml
  parameters:
    name: Windows
    os: windows
    envs: [py36-pyqt510]
